{% set name = 'telingo' %}
{% set dev = false %}
{% set version = '2.0.0' %}
{% if dev %}
{%   set build = 0 %}
{%   set rev = 'wip' %}
{% else %}
{%   set build = 0 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
{% if dev %}
  git_rev: {{ rev }}
  git_url: https://github.com/potassco/{{ name }}.git
{% else %}
  url: https://github.com/potassco/{{ name }}/archive/v{{ version }}.zip
{% endif %}

requirements:
  build:
    - clingo <=5.4.0
    - python
    - setuptools
  run:
    - clingo <=5.4.0
    - python

build:
  noarch: python
  number: {{ build }}
  script:
    - python setup.py test
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - telingo = telingo:main

test:
  commands:
    - telingo --version

about:
  home:  https://potassco.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.md
  summary: A solver for temporal logic programs.
  description: |
      Telingo is a solver for temporal logic programs.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}

