{% set name = 'clingolp' %}
{% set version = '0.1.0' %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  git_url: https://github.com/potassco/clingoLP.git

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - clingo >=5.4.0
    - lpsolve55

build:
  noarch: python
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

test:
  imports:
    - clingolp

about:
  home:  https://github.com/potassco/clingoLP
  license: GPL3
  license_family: GPL3
  license_file: LICENSE
  summary: clingo with theory propagator for linear programming 
  doc_url: https://github.com/potassco/clingoLP
  dev_url: https://github.com/potassco/clingoLP
