{% set name = 'clingo' %}
{% set version = "4.5.4" %}
{% set build = 0 %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://sourceforge.net/projects/potassco/files/clingo/{{ version }}/clingo-{{ version }}-source.tar.gz

requirements:
  build:
    - cmake
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - vc >=14 [win]
    - python
  run:
    - python

build:
  number: {{ build }}

test:
  commands:
    - clingo --version
    - reify --version
    - gringo --version

about:
  home:  https://potassco.org/
  license: MIT
  summary: A grounder and solver for logic programs.
  description: Clingo is an answer set programming (ASP) system that takes a logic program as input and calculates its answer sets.
  license_file: COPYING
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}
