{% set name = 'clingo' %}
{% set dev = true %}
{% if dev %}
{%   set version = "5.4.0" %}
{%   set build = 3 %}
{%   set rev = 'wip' %}
{% else %}
{%   set version = "5.3.0" %}
{%   set build = 0 %}
{% endif %}

package:
  name: {{ name }}
  version: {{ version }}

source:
{% if dev %}
  git_rev: {{ rev }}
  git_url: https://github.com/potassco/{{ name }}.git
{% else %}
  url: https://github.com/potassco/clingo/archive/v{{ version }}.tar.gz
{% endif %}

requirements:
  build:
    - cmake
{% if dev %}
    - win_flex_bison [win]
    - bison [not win]
    - m4 [not win]
    - re2c
{% endif %}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
  run:
    - python

build:
  number: {{ build }}
  skip: True [win and vc<14]

test:
  commands:
    - clingo --version
    - clasp --version
    - reify --version
    - lpconvert --version
    - gringo --version

about:
  home:  https://potassco.org/
  license: MIT
  summary: A grounder and solver for logic programs.
  description: Clingo is an answer set programming (ASP) system that takes a logic program as input and calculates its answer sets.
  license_file: LICENSE.md
  doc_url: https://potassco.org/
  dev_url: https://github.com/potassco/{{ name }}
