{% set version = '0.1.0' %}

package:
  name: clingo-lp
  version: {{ version }}

source:
  git_url: https://github.com/potassco/clingoLP.git
  git_rev: v{{ version }}

requirements:
  build:
    - setuptools
    - python
  run:
    - python
    - clingo >=5.4.0
    - lpsolve55

build:
  noarch: python
  number: 1  # NOTE: increment for new build/set to zero for new version
  script:
    - python setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - clingoLP = clingolp.app:main_clingo

test:
  imports:
    - clingolp

about:
  home:  https://github.com/potassco/clingoLP
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: clingo with theory propagator for linear programming
  doc_url: https://github.com/potassco/clingoLP
  dev_url: https://github.com/potassco/clingoLP
