python:
    - 2.7 [not win]
    - 3.5
    - 3.6
    - 3.7

clingo:
    - 5.4

pin_run_as_build:
    clingo: x.x

# from https://github.com/phracker/MacOSX-SDKs
CONDA_BUILD_SYSROOT:
    - /opt/MacOSX10.9.sdk # [osx]
